// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AritstItemInfo: typeof import('./src/components/artist-item/aritst-item-info.vue')['default']
    ArtistCate: typeof import('./src/components/artist/artist-cate.vue')['default']
    ArtistItemAlbum: typeof import('./src/components/artist-item/artist-item-album.vue')['default']
    ArtistItemInfo: typeof import('./src/components/artist-item/artist-item-info.vue')['default']
    ArtistItemMv: typeof import('./src/components/artist-item/artist-item-mv.vue')['default']
    ArtistItemSimi: typeof import('./src/components/artist-item/artist-item-simi.vue')['default']
    AudioList: typeof import('./src/components/zim-audio/audio-list.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    IndexHeader: typeof import('./src/components/index/index-header.vue')['default']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LoginModal: typeof import('./src/components/login-modal/login-modal.vue')['default']
    RecommendLatestMusic: typeof import('./src/components/recommend/recommend-latest-music.vue')['default']
    RecommendPrivateContent: typeof import('./src/components/recommend/recommend-private-content.vue')['default']
    RecommendSongs: typeof import('./src/components/recommend/recommend-songs.vue')['default']
    RecommendTitle: typeof import('./src/components/recommend/recommend-title.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/layout/search-input.vue')['default']
    SheetItem: typeof import('./src/components/song-sheet/sheet-item.vue')['default']
    ZimAside: typeof import('./src/components/layout/zim-aside.vue')['default']
    ZimAsideItem: typeof import('./src/components/zim-aside-item.vue')['default']
    ZimAudio: typeof import('./src/components/zim-audio/zim-audio.vue')['default']
    ZimHeader: typeof import('./src/components/layout/zim-header.vue')['default']
  }
}

export {}
